dist: xenial
services:
  - docker

before_install:
- wget -O- http://neuro.debian.net/lists/xenial.us-nh.full | sudo tee /etc/apt/sources.list.d/neurodebian.sources.list
- sudo apt-key add .travis.singularity_key.txt
- sudo apt-get update
- sudo apt-get install -y singularity-container

language: python
cache:
  pip: true
  directories:
    - .mypy_cache

os:
  - linux
install:
  - pip install tox-travis
jobs:
  include:
    - stage: test
      python: "3.6"
    - stage: test
      python: "3.7"
    - stage: test
      python: "3.8"
    - stage: test
      python: "3.9-dev"
    - stage: release-test
      python: "3.8"
      script: RELEASE_SKIP=head PYVER=3.8 ${TRAVIS_BUILD_DIR}/release-test.sh
script: tox
branches:
  only:
    - main
notifications:
  email: false
